### ISSUE TITLE
聯絡我們 contact.php 

### ISSUE THREAD

**Issue by willy800510** [willy800510/logoWeb#3]
>1. 右主欄  <#contSend>  送出後<.contactForm> 欄位想置換 -> 成功送出的欄位 <.sendSuccess>

**Comment by joyuhuang** [comment]
這個應該需要用ajax處理
[contact.zip](https://github.com/willy800510/logoWeb/files/6254987/contact.zip)
(有多建一個getContact.php來假裝PHP的處理部分)
ps. 表單我有多加了required 及 驗證樣式
