### ISSUE TITLE
模板 header.php 對齊問題

### ISSUE THREAD

**Issue by willy800510** [willy800510/logoWeb#6]
>1. header <lg 的右邊burger dropdown<#collapseMenu-sm>中的<#userCollapse>欄位想要對齊 “我的帳戶”

**Comment by joyuhuang** [comment]
https://github.com/willy800510/logoWeb/blob/a3d7af4a8512cb3e92d114fabe9ff3f0d7cb6453/logoweb/template/header.php#L69
改成這樣
`<div class="d-flex flex-column col-3 offset-3">`
看看符不符合你想要的效果

**Comment by willy800510** [comment]
有成功 謝謝
